[tool.poetry]
name = "caneta"
version = "0.1.0"
description = "Featured Printer"
authors = ["Antoine Gallix <antoine.gallix@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
